networks:
  caddy-proxy:
    external: true

secrets:
  couchlab-syncthing-api-key:
    file: ./secrets/couchlab-syncthing-api-key
  grafana-admin-password:
    file: ./secrets/admin-password
  white-lotus-syncthing-api-key:
    file: ./secrets/white-lotus-syncthing-api-key

services:
  # NOTE: install prometheus-node-exporter outside of docker
  prometheus:
    image: prom/prometheus:v3.8.0
    container_name: prometheus
    user: 1000:1000
    restart: unless-stopped
    command:
      - '--config.file=/prometheus/prometheus.yml'
      - '--log.level=debug'
    healthcheck:
      test: wget --timeout=15 --quiet --tries=1 --spider http://localhost:9090/ || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
      start_interval: 1s
    labels:
      wud.tag.include: '^v\d+\.\d+\.\d+$$'
      wud.link.template: 'https://github.com/prometheus/prometheus/releases/tag/v$${major}.$${minor}.$${patch}'
    networks:
      - caddy-proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - white-lotus-syncthing-api-key
      - couchlab-syncthing-api-key
    volumes:
      - ${PROM_DATA_DIR:?PROM_DATA_DIR is not set}:/prometheus
      - ./prometheus.yml:/prometheus/prometheus.yml
    logging:
      options:
        max-size: "10M"
        max-file: "5"

  grafana:
    image: grafana/grafana:12.2.0
    container_name: grafana
    user: 1000:1000
    depends_on:
      prometheus:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - caddy-proxy
    labels:
      wud.tag.include: '^v\d+\.\d+\.\d+$$'
      wud.link.template: 'https://github.com/grafana/grafana/releases/tag/v$${major}.$${minor}.$${patch}'
    secrets:
      - grafana-admin-password
    environment:
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana-admin-password
    # NOTE: I highly recommend putting this on an SSD
    volumes:
      - ${GRAFANA_DATA_DIR:?GRAFANA_DATA_DIR is not set}:/var/lib/grafana
