# This configuration file updates the default configuration file
# See https://github.com/searxng/searxng/blob/master/searx/limiter.toml

[botdetection]
trusted_proxies = [
         '127.0.0.1/32',
         '192.168.50.0/24',
         '10.1.0.0/16',
         '::1',
         '2001:db8::/56',
        # BEGIN CLOUDFLARE IPs
         '173.245.48.0/20',
         '103.21.244.0/22',
         '103.22.200.0/22',
         '103.31.4.0/22',
         '141.101.64.0/18',
         '108.162.192.0/18',
         '190.93.240.0/20',
         '188.114.96.0/20',
         '197.234.240.0/22',
         '198.41.128.0/17',
         '162.158.0.0/15',
         '104.16.0.0/13',
         '104.24.0.0/14',
         '172.64.0.0/13',
         '131.0.72.0/22',
         '2400:cb00::/32',
         '2606:4700::/32',
         '2803:f800::/32',
         '2405:b500::/32',
         '2405:8100::/32',
         '2a06:98c0::/29',
         '2c0f:f248::/32',
        # END CLOUDFLARE IPs
]

[botdetection.ip_limit]
# activate advanced bot protection
# enable this when running the instance for a public usage on the internet
link_token = true

[botdetection.ip_lists]
pass_ip = [
  "192.168.50.0/24",
]
