http:
  routers:
    syncthing:
      entrypoints:
        - 'http'
        - 'https'
      middlewares:
        - default-security-headers
        - https-redirectscheme
      rule: Host(`syncthing.{{env "BASE_DOMAIN"}}`)
      tls:
        certResolver: cloudflare
      service: syncthing
  services:
    syncthing:
      loadBalancer:
        healthcheck:
          path: /rest/noauth/health
        servers:
          - url: 'http://host.docker.internal:8384/'
          - url: 'https://host.docker.internal:8384/'

  middlewares:
    unsafe-csp:
      headers:
        # no embeds still
        contentSecurityPolicy: >
          default-src https: data: blob:;
          frame-ancestors 'none';
          object-src 'none';
          script-src 'self' *.{{ env "BASE_DOMAIN" }} 'unsafe-inline';
          style-src 'self' *.{{ env "BASE_DOMAIN" }} 'unsafe-inline';
    strict-csp:
      headers:
        contentSecurityPolicy: >
          default-src 'self' *.{{ env "BASE_DOMAIN" }};
          frame-ancestors 'none';
          img-src 'self' *.{{ env "BASE_DOMAIN" }} blob: data:;
          object-src 'none';
          script-src 'self' *.{{ env "BASE_DOMAIN" }};
          style-src 'self' *.{{ env "BASE_DOMAIN" }};
    default-security-headers:
      headers:
        browserXSSFilter: true
        customBrowserXSSValue: 0                            # X-XSS-Protection=1; mode=block
        contentTypeNosniff: true                          # X-Content-Type-Options=nosniff
        forceSTSHeader: true                              # Add the Strict-Transport-Security header even when the connection is HTTP
        frameDeny: false                                   # see below
        referrerPolicy: "strict-origin-when-cross-origin"
        SSLHost: {{env "BASE_DOMAIN"}}
        SSLRedirect: true
        stsIncludeSubdomains: true                        # Add includeSubdomains to the Strict-Transport-Security header
        stsPreload: true                                  # Add preload flag appended to the Strict-Transport-Security header
        stsSeconds: 3153600                              # Set the max-age of the Strict-Transport-Security header (63072000 = 2 years)
        hostsProxyHeaders:
          - X-Forwarded-Host
        customRequestHeaders:
          X-Frame-Options: sameorigin
          X-Forwarded-Proto: https
          X-Robots-Tag: none,noarchive,nosnippet,notranslate,noimageindex,
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

tls:
  options:
    default:
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
      sniStrict: true
