networks:
  caddy-proxy:
    external: true

secrets:
  le-cert:
    file: ../caddy/certs/wildcard_.couchlab.me.crt
  le-key:
    file: ../caddy/certs/wildcard_.couchlab.me.key

services:
  adguard-home:
    image: adguard/adguardhome:v0.107.71
    container_name: adguard-home
    restart: unless-stopped
    hostname: adguard
    # modified from a solution found here: https://github.com/AdguardTeam/AdGuardHome/issues/3290
    # AGH team claims healthchecks cause issues
    healthcheck:
      test: nslookup adguard-home.${BASE_DOMAIN:?BASE_DOMAIN is not set} 127.0.0.1 || exit 1
      interval: 60s
      timeout: 5s
      retries: 1
      start_period: 30s
      # sometimes, nslookup can take a second or two
      start_interval: 3s
    # NOTE: enable these in Encryption settings or by manually editing the config
    secrets:
      - le-cert
      - le-key
    networks:
      caddy-proxy:
        ipv4_address: 10.1.1.10
    labels:
      wud.tag.include: '^v\d\.\d+\.\d+$$'
      wud.link.template: 'https://github.com/AdguardTeam/AdGuardHome/releases/tag/v$${major}.$${minor}.$${patch}'
    ports:
      # DNS
      - 53:53/tcp
      - 53:53/udp
      - 853:853/tcp
      - 853:853/udp
      # handled by traefik
      # NOTE: make sure to set admin web UI port to the traefik load balancer port in setup!
      # - 80:80/tcp
      # - 443:443/tcp
      # - 443:443/udp
      # - 3000:3000/tcp
    volumes:
      - ${ADGUARD_DIR:?ADGUARD_DIR is not set}/work:/opt/adguardhome/work
      - ${ADGUARD_DIR:?ADGUARD_DIR is not set}/config:/opt/adguardhome/conf

  adguard-exporter:
    image: ghcr.io/henrywhitaker3/adguard-exporter:latest
    container_name: adguard-exporter
    restart: unless-stopped
    depends_on:
      adguard-home:
        condition: service_healthy
    env_file: exporter.env
    networks:
      - caddy-proxy
    labels:
      wud.tag.include: latest
      wud.watch.digest: true
